var mongoose = require("mongoose");
var Schema = mongoose.Schema;

var studentSchema = new Schema({
    "title" : String,
    "firstName": String,
    "lastName": String,
    "fullName": String,
    "image": String,
    "phone": String,
    "email": String,
    "adharCardNumber": String,
    "fatherName": String,
    "fatherPhone": String,
    "fatherEmail": String,
    "motherName": String,
    "motherPhone": String,
    "motherEmail": String,
    "gender": String,
    "class": String,
    "password": String,
    "classTeacher": String,
    "payment": String,
    "paymentStatus": String,
    "totalPayment":String,
    "pendingPayment":String,
    "schoolId": { type: Schema.Types.ObjectId, ref: "school" },
    "address": String,
    "city": String,
    "zipcode": String,
    "state": String,
    "country": {type: String, default: "India" },
    "role":  {type: String, default: "Student" },
    "status":  {type: String, default: "Active" },
    "isDeleted": {type: Boolean, default: false },
    "createdDate": { type: Date, default: Date.now },
    "updatedDate": { type: Date },
});
module.exports = mongoose.model('student', studentSchema);